### ISSUE TITLE
功能建议：增加隐藏目录栏和分页条的功能

### ISSUE THREAD

**Issue by ttpcy** [henryxrl/SimpleTextReader#13]
感谢大佬的软件，功能简单直接明朗，非常好用！

使用中发现个小需求：
因为沉浸阅读时并不需要随时关注章节目录、分页条等，能否增加隐藏选项或自动隐藏功能，其实就类似手机版的阅读工具了。

不知开发难度如何，只是提出小建议，望考虑。

**Comment by henryxrl** [comment]
分页条是可以隐藏的——设置里面有个分页条透明度，设置为 0 即可。鼠标划过时会自动显示。
至于章节目录，暂时不会做隐藏相关的设置。不过以后有时间会给竖屏（比如手机）适配，那时目录不得不自动隐藏。
