### ISSUE TITLE
建议标题和作者的语言可以不要自动变成繁体中文

### ISSUE THREAD

**Issue by xzyl4303** [henryxrl/SimpleTextReader#14]
# 建议标题和作者的语言可以不要自动变成繁体中文，可以设置。
谢谢

**Comment by henryxrl** [comment]
能贴一张截图给我看看吗？

**Comment by xzyl4303** [comment]
![Screenshot 2023-12-22 10 48 07](https://github.com/henryxrl/SimpleTextReader/assets/115838895/f83a9f6f-889b-434c-8c01-753e0377f9ec)
![Screenshot 2023-12-22 10 48 28](https://github.com/henryxrl/SimpleTextReader/assets/115838895/624bfad2-4a25-4f0a-9ccd-6046e1966466)

**Comment by henryxrl** [comment]
这个字体（齐伋体）就是这样的，因为是一种仿古刻本字体，所以都会用繁体字表示，具体可看：[https://github.com/LingDong-/qiji-font](https://github.com/LingDong-/qiji-font)

**Comment by xzyl4303** [comment]
那可以添加更改简体中文字体的功能
