### ISSUE TITLE
增加更换字体的设置。

### ISSUE THREAD

**Issue by meinaOfficial** [henryxrl/SimpleTextReader#18]
楷体固然好看，但是长期使用电脑，现在更喜欢雅黑，有人也会喜欢别的字体，建议多内置几个字体，或者可以调用浏览器的字体。跪求！

**Comment by henryxrl** [comment]
调用浏览器的字体似乎可行。

**Comment by meinaOfficial** [comment]
看作者喽，咱就是个大废物，只会动嘴。


________________________________
发件人: Henry Xu ***@***.***>
发送时间: Friday, June 7, 2024 4:09:18 AM
收件人: henryxrl/SimpleTextReader ***@***.***>
抄送: meinaOfficial ***@***.***>; Author ***@***.***>
主题: Re: [henryxrl/SimpleTextReader] 增加更换字体的设置。 (Issue #18)


调用浏览器的字体似乎可行。

―

**Comment by henryxrl** [comment]
已更新 v1.5
