### ISSUE TITLE
自动分页逻辑是否存在问题？

### ISSUE THREAD

**Issue by XuanFengQing** [henryxrl/SimpleTextReader#19]
对于能识别出章节的小说来说，会导致有的章节被分到相邻两页的末尾和开始，这对很棒的自动识别章节并且分章功能来说是一种破坏，让人很难受。大佬，这有办法解决吗？

**Comment by henryxrl** [comment]
暂时就先沿用目前的分页规则吧，目前没有想到一个特别优雅的分页方案。之前想过每个章节一页，但如果自动识别不准确就会造成非常长的页面，甚至影响阅读体验。如果有想法的话也欢迎告知！

**Comment by henryxrl** [comment]
已在 v1.5.6 版中解决
