### ISSUE TITLE
分页条的优化建议，以及其他的优化。

### ISSUE THREAD

**Issue by Sucorde** [henryxrl/SimpleTextReader#20]
分页条目前遮挡了部分文字，阅读体验不是很好。
目前我只想到三个点：
第一个是放在右侧变成竖条，这样就不遮挡了。
第二个是让它有目录的隐藏功能，鼠标不在组件上就隐藏。
第三个是设置里面可以关闭。

书架上的字体颜色建议同步设置内的字体颜色。否则在有些背景颜色上面会看不到书名。

设置内组件名称是否可以使用反色？因为目前是跟主题颜色挂钩的。有些背景下看不清楚。

还有一点，就是左侧的章节名称显示不全。只能显示章节，章节名称被截断了。

还有一个，是否可以出一个本地架设的教程？

**Comment by Sucorde** [comment]
还有一点，就是左侧的章节名称显示补全。只能显示章节，章节名称被截断了。

**Comment by henryxrl** [comment]
1. 分页条可以设置透明度——当透明度为 0 的时候，分页条就隐藏了，鼠标移到分页条附近时分页条会显示。
2. 字体颜色的两点，可否截图？
3. 左侧章节名称被截断是肯定会发生的，因为章节名称长度不固定。但是对于截断的章节名称，末尾会有 “...” 作为提示，当鼠标悬停时，会有完整的章节名称显示：
![ce3btu2q q5g](https://github.com/user-attachments/assets/59b617e9-5011-4028-9a61-1c045174fdd1)
4. 本地部署可以用 electron，Tauri，Nativefier，Pake 等工具打包。可以看看[这里](https://meta.appinn.net/t/topic/45732)和[这里](https://meta.appinn.net/t/topic/50710)。

**Comment by Sucorde** [comment]
![image](https://github.com/user-attachments/assets/752486e0-a542-4469-b147-b421e8b133ee)

**Comment by henryxrl** [comment]
现在封面字体的颜色用的是背景颜色——建议把主题颜色和背景颜色区分的更大些（比如，把主题颜色设置的浅一些），如图：
![image](https://github.com/user-attachments/assets/f55f7195-b018-4acb-9ca8-3b9c6299ddfe)

**Comment by Sucorde** [comment]
你看我设置，我字体设置的是白色啊。

**Comment by henryxrl** [comment]
封面字体颜色用的是背景颜色，所以是黑的

**Comment by Sucorde** [comment]
好的，我只看图了，哈哈。好吧。
