### ISSUE TITLE
章节标题识别有字数上限，一些超长的标题会识别不出来，想自己修改标题正则请问去哪里改

### ISSUE THREAD

**Issue by sqsq37** [henryxrl/SimpleTextReader#21]
rt
章节标题识别有字数上限，一些超长的标题会识别不出来，想自己修改标题正则请问去哪里改

**Comment by sqsq37** [comment]
我自己修改了regex_rules.js里的正则，然后显示文件已损坏

**Comment by henryxrl** [comment]
我来改吧！上限要多少？如果可能的话最好把 txt 文件给我做测试

**Comment by sqsq37** [comment]
50不够，这个第五章就99个字符了
![image](https://github.com/user-attachments/assets/4e78bf8a-cf76-43da-8427-74841244c9c6)

**Comment by sqsq37** [comment]
[[深海10光年] 淫魔的道具店与肉体改造色情陷阱地牢.txt](https://github.com/user-attachments/files/17383625/10.txt)

**Comment by henryxrl** [comment]
兄弟兴趣广泛啊！

在最新的 v1.5 版本里解决了。
