### ISSUE TITLE
edge插件似乎有bug？

### ISSUE THREAD

**Issue by kuzers** [henryxrl/SimpleTextReader#22]
发现有书没办法读取出来，点进去处于空白状态![IMG_20241203_035838.jpg](https://github.com/user-attachments/assets/e0955a76-dea0-4671-8b58-a2c8fc280bae)

![IMG_20241203_035827.jpg](https://github.com/user-attachments/assets/48f1ef75-4a08-4b96-aacf-3342778fb185)

**Comment by kuzers** [comment]
![IMG_20241204_012130.jpg](https://github.com/user-attachments/assets/12fc00e6-5255-4d7b-a8e4-8a4d91ee1d51)

唔 似乎并未解决，那还是等新版本吧

**Comment by kuzers** [comment]
![IMG_20241204_015350.jpg](https://github.com/user-attachments/assets/90df66c3-ed40-4011-9506-0243586598b6)

火狐是1.6.3，但还是不行，我把书发给大佬吧

**Comment by kuzers** [comment]
[超神机械师.txt](https://github.com/user-attachments/files/17997101/default.txt)
[六朝清羽记.txt](https://github.com/user-attachments/files/17997105/default.txt)

**Comment by henryxrl** [comment]
问题解决了，跟章节名称有关。我还发现一些后续的优化可以做，所以过几天再更新。

不过我有一点点建议哈，在用易笺打开之前，可以看看章节名称的样式。比如你的《六朝清羽记》里，章节名称是这样的：`第1章·穿越` —— 这并不是比较通用的样式，最好把它们替换成较通用的样式，例如 `第1章 穿越`（把中间的点换成空格）。

还有，可以把文件名变成 `《书名》作者：作者.txt` 这样的格式（英文书可以 `book by author.txt`），方便易笺提取信息。你可以试试我简单处理过的文件。

[《六朝清羽记》作者：弄玉＆龙琁.txt](https://github.com/user-attachments/files/17997640/default.txt)

**Comment by henryxrl** [comment]
[《超神机械师》作者：齐佩甲.txt](https://github.com/user-attachments/files/17999288/default.txt)

**Comment by kuzers** [comment]
谢谢大佬，辛苦了😘😘😘😘😘😘😘

**Comment by kuzers** [comment]
因为之前的1.5版本是能打开来的（所以一直在书架里），更新之后就打不开了，我想大概和新的分页逻辑有关

**Comment by henryxrl** [comment]
嗯嗯，新的分页模式太复杂了，自己给自己挖了个坑 😭 ……  过几天我看看能不能完全解决

**Comment by henryxrl** [comment]
v1.6.4 解决了。我还没正式发布，但你可以去测试网站试试看：http://txt.xrl.app

Bug 的原因是没检测到任何有效标题，所以分页就无法进行了。最新版本修复了这个问题。分页功能应该一切正常了。

在这基础上，我又写了另一个 feature：代码现在可以通过分析小说内容，自动生成符合当前小说章节名称的正则表达式。这个就有点牛逼了容我得瑟一下～ 估计现在市面上还没有哪个阅读器有这个功能的。但还是需要大量测试～ 你提供的两本书，即使不做任何更改也应该可以提取到标题了！

**Comment by kuzers** [comment]
谢谢大佬啦，膜拜膜拜😍😍😍😍😍
