### ISSUE TITLE
屏幕分辨率（缩放与布局，浏览器页面）致使易笺设置菜单显示不全的问题

### ISSUE THREAD

**Issue by kuzers** [henryxrl/SimpleTextReader#24]
![IMG_20241221_184553.jpg](https://github.com/user-attachments/assets/73616900-8e28-4d7b-a865-5c3b43f0b970)

第一排书显示不全，和设置最上方被挡住

**Comment by kuzers** [comment]
第一排书籍显示不全好像是显示屏幕横竖屏切换之后会触发

**Comment by kuzers** [comment]
当然，正常横屏看点进一本书然后退出好像也有点问题![IMG_20241221_185531.jpg](https://github.com/user-attachments/assets/a60de525-7bb6-4cb9-b7a3-d13f5320d9da)

这是正常的情况![正在上传 IMG_20241221_185545.jpg…]()

这是出现了一点问题，最上面被卡掉了

**Comment by henryxrl** [comment]
对，这个 bug 我在 v1.6.6 版本已经修复了。这个版本目前还没有正式发布，你可以去 https://txt.xrl.app 这个测试版地址试试~

**Comment by kuzers** [comment]
当然，正常横屏看点进一本书然后退出好像也有点问题![IMG_20241221_185531.jpg](https://github.com/user-attachments/assets/a60de525-7bb6-4cb9-b7a3-d13f5320d9da)

这是正常的情况![正在上传 IMG_20241221_185545.jpg…]()

这是出现了一点问题，最上面被卡掉了

**Comment by kuzers** [comment]
豪的，第一排书籍的bug解决了，但是设置最上行显示不出来没好，屏幕太小就没法显示全吗，好像之前不是这样的啊![IMG_20241222_001049.jpg](https://github.com/user-attachments/assets/e03253c1-821d-4dd8-a0cf-2593addb4ad8)

**Comment by kuzers** [comment]
竖着就没啥问题![IMG_20241222_001332.jpg](https://github.com/user-attachments/assets/341ee6db-68f9-4426-a289-feb89efdb4b5)

**Comment by henryxrl** [comment]
我倒是没有改设置菜单的大小……

你屏幕的分辨率是多少？

**Comment by kuzers** [comment]
一个蛮奇怪的分辨率吧（），这是一个小平板（小米平板2），2048*1536

**Comment by kuzers** [comment]
哦，我大概知道了

**Comment by kuzers** [comment]
![IMG_20241222_002820.jpg](https://github.com/user-attachments/assets/b7de2abe-5c94-410f-b551-995acde87dbf)

如果是我正常的200％预设就会出现设置显示不全

**Comment by kuzers** [comment]
我怎么记得以前好像没这个问题😂，如果这个不好做的话其实倒也无伤大雅（如果能让设置也可以上下滑动，设置能容就能够都显示完全了）

**Comment by henryxrl** [comment]
200% 的话就是等效 1024*768 的分辨率了，我确实没在这样的分辨率下测试过。我之后想想办法！
如果测试版有什么问题，欢迎告知！没什么问题的话过几天我就发布了～

对了，测试版支持自定义字体的哦！直接把字体文件拖进去即可。

**Comment by kuzers** [comment]
豪的，谢谢大佬的付出，让我们更爽的看小说😘😘😘

**Comment by kuzers** [comment]
我又试了又试。好像发现了问题![IMG_20241222_013528.jpg](https://github.com/user-attachments/assets/dbc789f9-f06b-45bf-974a-37b1052a52ee)

![IMG_20241222_013606.jpg](https://github.com/user-attachments/assets/fa5262f8-ea31-4275-95ac-f2e5dc450406)
![IMG_20241222_013853.jpg](https://github.com/user-attachments/assets/5e7ac745-d588-4413-9c29-722d8fe8e63b)



当这个易笺的窗口变小时，易笺设置并不会跟随变化。所以就出现了显示不全的问题，其他问题似乎在1.6.6解决了

**Comment by henryxrl** [comment]
感谢测试！对，目前设置菜单并不能随窗口大小变化而变化。具体怎么实现我还得再想想～

为什么 slider 的底色是黑的？能把你的颜色配置给我吗？
![image](https://github.com/user-attachments/assets/d251375b-54c9-4107-b7a2-7e48573d10b7)

**Comment by kuzers** [comment]
我又试了又试。好像发现了问题![IMG_20241222_013528.jpg](https://github.com/user-attachments/assets/dbc789f9-f06b-45bf-974a-37b1052a52ee)

![IMG_20241222_013606.jpg](https://github.com/user-attachments/assets/fa5262f8-ea31-4275-95ac-f2e5dc450406)
![IMG_20241222_013853.jpg](https://github.com/user-attachments/assets/5e7ac745-d588-4413-9c29-722d8fe8e63b)



当这个易笺的窗口变小时，易笺设置并不会跟随变化。所以就出现了显示不全的问题，其他问题似乎在1.6.6解决了

**Comment by kuzers** [comment]
所以其实和屏幕分辨率的问题并没有关系吧（我有点理不清了，小白一个）,slider的底色问题是因为我开着一个插件dark reader![IMG_20241222_014710.jpg](https://github.com/user-attachments/assets/bd9fd37b-2101-4287-8ee9-7d60a315cb80)

关了就没事了

**Comment by henryxrl** [comment]
现在菜单大小是一个定值，比如 500x800. 如果分辨率低于这个，菜单就会超出视口之外。你想要的是能动态调整大小（以及菜单界面里所有元素的大小）的菜单。我得想想该怎么实现。

易笺支持暗黑模式的～ 所以也可以把易笺从 Dark Reader 里排除哈哈

**Comment by kuzers** [comment]
所以其实和屏幕分辨率的问题并没有关系吧（我有点理不清了，小白一个）,slider的底色问题是因为我开着一个插件dark reader![IMG_20241222_014710.jpg](https://github.com/user-attachments/assets/bd9fd37b-2101-4287-8ee9-7d60a315cb80)

关了就没事了

**Comment by kuzers** [comment]
哈哈哈，好的，算是终于发现问题了。麻烦大佬了🌹🌹🌹🌹

**Comment by henryxrl** [comment]
我好像是搞定了……

![2024-12-21 15 36 51](https://github.com/user-attachments/assets/ccfb1527-f732-4511-afe2-c58362e0b9d1)

**Comment by kuzers** [comment]
大佬辛苦咯🙏🙏🙏🙏，期待在新版上能够解决

**Comment by henryxrl** [comment]
https://txt.xrl.app 已经更新了，你可以试试看。
过两天我争取搞一个正式的 beta 版网址，方便大家尝鲜。

**Comment by kuzers** [comment]
https://github.com/user-attachments/assets/aa76285f-091a-46a1-bc88-c8e01dbf8636

这样就好很多了，谢谢大佬❤️（设置能塞更多功能了૧(●´৺`●)૭）
https://github.com/user-attachments/assets/d7f2fd01-8aa6-464f-83c7-6e7aadca099d
菜单大小目前还是固定的，浏览器的长最多缩小成餐单大小。
https://github.com/user-attachments/assets/a6aea695-0d24-4f7b-910f-3555b9e8c4c2

如果这个要适配的话感觉有点难度，但其实问题不大，可以不用做，这个视口大小，书也不方便看

**Comment by henryxrl** [comment]
嗯嗯，那么小的窗口我就偷个懒，不搞单独缩放菜单之类的了，确实看书也不方便~ 大不了先设置，再看书。

看了你录制的视频，我觉得在非极端情况下，设置菜单都能用了。👍

**Comment by kuzers** [comment]
https://github.com/user-attachments/assets/aa76285f-091a-46a1-bc88-c8e01dbf8636

这样就好很多了，谢谢大佬❤️（设置能塞更多功能了૧(●´৺`●)૭）
https://github.com/user-attachments/assets/d7f2fd01-8aa6-464f-83c7-6e7aadca099d
菜单大小目前还是固定的，浏览器的长最多缩小成餐单大小。
https://github.com/user-attachments/assets/a6aea695-0d24-4f7b-910f-3555b9e8c4c2

如果这个要适配的话感觉有点难度，但其实问题不大，可以不用做，这个视口大小，书也不方便看

**Comment by kuzers** [comment]
好的，辛苦大佬了(´∇ﾉ｀*)ノ
