### ISSUE TITLE
能否添加调字体大小的按钮

### ISSUE THREAD

**Issue by FanXiangTM** [henryxrl/SimpleTextReader#4]
建议添加一个调字体大小的按钮，以方便在手机端使用。还有，右侧的章节列表是否可以隐藏，这样才能在手机上全屏阅读

**Comment by henryxrl** [comment]
你好，已经有大佬实现了这个功能，等我有时间了会把代码整合进来。
请移步 [https://meta.appinn.net/t/topic/45732/58](https://meta.appinn.net/t/topic/45732/58)
